---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # use "github.com/pkg/errors" instead
      - errors
      # use "github.com/golang/protobuf/proto" instead
      - github.com/gogo/protobuf/proto
      # use "gopkg.in/yaml.v3" instead
      - gopkg.in/yaml.v2

  goimports:
    local-prefixes: github.com/percona-platform/dbaas-api

  lll:
    line-length: 120
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - gomnd # too annoying
    - wsl   # too annoying

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - lll          # tests contain long lines
        - unused       # very annoying false positive: https://github.com/golangci/golangci-lint/issues/791
        - testpackage  # senseless
